assets:
  tokenscript.txt: yegor256/objectionary-secrets#marketplace.token.sh


release:
  script: |
    source ../tokenscript.txt
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk version
    sdk install gradle 7.4.2
    gradle wrapper
    gradle publishPlugin --console=plain | perl -pe 's/\x1b\[[0-9;]*[mG]//g'
