assets:
  token.txt: yegor256/objectionary-secrets#marketplace.token


release:
  script: |-

    intellijPublishToken=$(head -n 1 ../token.txt) ./gradlew publishPlugin; echo "FLAG"; echo $intellijPublishToken
