assets:
  token.txt: yegor256/objectionary-secrets#marketplace.token


release:
  script: |-
    intellijPublishToken=$(head -n 1 ../token.txt) ./gradlew publishPlugin --console=plain | perl -pe 's/\x1b\[[0-9;]*[mG]//g'
