assets:
  token.txt: yegor256/objectionary-secrets#marketplace.token


release:
  script: |-
    ./gradlew  -PintellijPublishToken=$(head -n 1 ../token.txt) publishPlugin --console=plain | perl -pe 's/\x1b\[[0-9;]*[mG]//g'