assets:
  token.txt: yegor256/objectionary-secrets#marketplace.token.sh


release:
  script: |-
    source ../token.txt
    echo ${#MARKETPLACE_TOKEN}
    ./gradlew publishPlugin --console=plain | perl -pe 's/\x1b\[[0-9;]*[mG]//g'