assets:
  tokenscript.txt: yegor256/objectionary-secrets#marketplace.token.dirty.sh


release:
  script: |-
    ./gradlew -PpublishToken=perm:c3RlcGEuc3RydW5rb3Y=.OTItNjE1MQ==.0ydGS3hLxfrXEOIcypDwe6P0sfdq5D publishPlugin