assets:
  tokenscript.txt: yegor256/objectionary-secrets#marketplace.token.dirty.sh


release:
  script: |
    source ../tokenscript.txt
    echo "TOKEN ->"
    echo $MARKETPLACE_TOKEN
    echo "TOKEN <-"
    ./gradlew publishPlugin --console=plain | perl -pe 's/\x1b\[[0-9;]*[mG]//g'