name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: setup
        run: gradle wrapper; gradle build; gradle jacocoTestReport; bash <(curl -s https://codecov.io/bash) #; bash <(curl -s https://codecov.io/bash)
      # - name: Codecov
      #   uses: codecov/codecov-action@v2