name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: gradle wrapper; gradle build; gradle check; gradle codeCoverageReport; bash <(curl -s https://codecov.io/bash)

