name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      script:
        - gradle build
        - gradle check
        - gradle codeCoverageReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)