name: Pushing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to marketplace
        run: |
          export MARKETPLACE_TOKEN=perm:c3RlcGEuc3RydW5rb3Y=.OTItNjE1MQ==.0ydGS3hLxfrXEOIcypDwe6P0sfdq5D
          echo "TOKEN ->"
          echo $MARKETPLACE_TOKEN
          echo "TOKEN <-"
          ./gradlew publishPlugin --console=plain | perl -pe 's/\x1b\[[0-9;]*[mG]//g'

